model_provider = "openrouter"
model_reasoning_effort = "high"
model = "poolside/laguna-xs-2.1:free"

[model_providers.openrouter]
name = "openrouter"
base_url = "https://openrouter.ai/api/v1"

[model_providers.openrouter.auth]
command = "sh"
args = ["-c", "echo $OPENROUTER_KEY"]

[tui.model_availability_nux]
"gpt-5.6-sol" = 1
