[tools]
bun = "latest"
go = "1.23.10"
node = "latest"
deno = "latest"
rust = "latest"
java = "temurin-21.0.11+10.0.LTS"
python = "latest"
ruby = "latest"
rust-analyzer = "latest"
clang = "22.1.4"
cmake = "4.3.2"
