return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  cmd = { "MasonToolsInstall", "MasonToolsInstallSync", "MasonToolsUpdate", "MasonToolsClean" },
  event = { "BufReadPost", "BufNewFile" },
  dependencies = { "mason-org/mason.nvim" },
  opts = {
    ensure_installed = {
      "gofumpt",
      "goimports",
      "golangci-lint",
      "markdownlint-cli2",
      "prettierd",
      "ruff",
      "sql-formatter",
      "shellcheck",
      "shfmt",
      "stylua",
      "taplo",
      "yamllint",
    },
    auto_update = false,
    run_on_start = true,
    start_delay = 500,
  },
}
