return {
  "hedyhli/outline.nvim",
  cmd = { "Outline", "OutlineOpen", "OutlineClose" },
  keys = {
    { "<leader>so", "<cmd>Outline<cr>", desc = "Toggle Symbols Outline" },
  },
  opts = {
    outline_window = {
      position = "right",
      relative_width = true,
      width = 25,
      auto_close = false,
      show_numbers = false,
      show_relative_numbers = false,
      wrap = false,
      show_cursorline = true,
      hide_cursor = false,
      jump_highlight_duration = 300,
    },
    outline_items = {
      show_symbol_details = true,
      show_symbol_lineno = false,
      highlight_hovered_item = true,
      auto_set_cursor = true,
      auto_unfold_hover = true,
    },
    preview_window = {
      auto_preview = false,
      open_hover_on_preview = false,
      width = 50,
      min_width = 50,
      relative_width = 0.5,
      border = "single",
    },
    symbols = {
      filter = nil,
      icon_fetcher = nil,
      icon_source = nil,
      icons = {
        File = { icon = "", hl = "Identifier" },
        Module = { icon = "", hl = "@namespace" },
        Namespace = { icon = "", hl = "@namespace" },
        Package = { icon = "", hl = "@namespace" },
        Class = { icon = "𝓒", hl = "@type" },
        Method = { icon = "ƒ", hl = "@method" },
        Property = { icon = "", hl = "@method" },
        Field = { icon = "", hl = "@field" },
        Constructor = { icon = "", hl = "@constructor" },
        Enum = { icon = "", hl = "@type" },
        Interface = { icon = "", hl = "@type" },
        Function = { icon = "", hl = "@function" },
        Variable = { icon = "", hl = "@constant" },
        Constant = { icon = "", hl = "@constant" },
        String = { icon = "𝓐", hl = "@string" },
        Number = { icon = "#", hl = "@number" },
        Boolean = { icon = "", hl = "@boolean" },
        Array = { icon = "", hl = "@constant" },
        Object = { icon = "", hl = "@type" },
        Key = { icon = "🔐", hl = "@type" },
        Null = { icon = "NULL", hl = "@type" },
        EnumMember = { icon = "", hl = "@field" },
        Struct = { icon = "𝓢", hl = "@type" },
        Event = { icon = "🗲", hl = "@type" },
        Operator = { icon = "+", hl = "@operator" },
        TypeParameter = { icon = "𝙏", hl = "@parameter" },
        Component = { icon = "", hl = "@function" },
        Fragment = { icon = "", hl = "@constant" },
      },
    },
    keymaps = {
      close = { "<Esc>", "q" },
      goto_location = "<Cr>",
      peek_location = "o",
      goto_and_close = "<S-Cr>",
      restore_location = "<C-g>",
      hover_symbol = "<C-space>",
      toggle_preview = "K",
      rename_symbol = "r",
      code_actions = "a",
      fold = "h",
      unfold = "l",
      fold_all = "W",
      unfold_all = "E",
      fold_reset = "R",
      down_and_jump = "<C-j>",
      up_and_jump = "<C-k>",
    },
    providers = {
      priority = { "lsp", "coc", "markdown", "norg" },
      lsp = {
        blacklist_clients = {},
      },
    },
  },
}
